# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  simple:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Run a one-line script
        run: echo Hello

  job1:
    runs-on: ubuntu-latest
    outputs:
        output1: ${{ steps.make.outputs.out}}
    steps:
      - id: make
        run: echo "out=output" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        version: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"- ${{ matrix.version }}
